
@include('admin.layouts.partials.crud-components.filter', [
    'create_route' => $create_route,
    'filters' => [
        [
            'type' => 'text',
            'name' => 'filter[title]',
            'label' => 'title',
            'required' => 'false',
            'placeholder' => 'title',
        ],
        [
            'type' => 'text',
            'name' => 'filter[description]',
            'label' => 'description',
            'required' => 'false',
            'placeholder' => 'description',
        ],
        [
            'type' => 'text',
            'name' => 'filter[category]',
            'label' => 'category',
            'required' => 'false',
            'placeholder' => 'category',
        ],
        [
            'type' => 'number',
            'name' => 'filter[price]',
            'label' => 'price',
            'required' => 'false',
            'placeholder' => 'price',
        ],
        [
            'type' => 'number',
            'name' => 'filter[discountPercentage]',
            'label' => 'discountPercentage',
            'required' => 'false',
            'placeholder' => 'discountPercentage',
        ],
        [
            'type' => 'number',
            'name' => 'filter[rating]',
            'label' => 'rating',
            'required' => 'false',
            'placeholder' => 'rating',
        ],
        [
            'type' => 'number',
            'name' => 'filter[stock]',
            'label' => 'stock',
            'required' => 'false',
            'placeholder' => 'stock',
        ],
        [
            'type' => 'text',
            'name' => 'filter[sku]',
            'label' => 'sku',
            'required' => 'false',
            'placeholder' => 'sku',
        ],
        [
            'type' => 'text',
            'name' => 'filter[brand]',
            'label' => 'brand',
            'required' => 'false',
            'placeholder' => 'brand',
        ],
        [
            'type' => 'text',
            'name' => 'filter[warrantyInformation]',
            'label' => 'warrantyInformation',
            'required' => 'false',
            'placeholder' => 'warrantyInformation',
        ],
        [
            'type' => 'text',
            'name' => 'filter[shippingInformation]',
            'label' => 'shippingInformation',
            'required' => 'false',
            'placeholder' => 'shippingInformation',
        ],
        [
            'type' => 'text',
            'name' => 'filter[availabilityStatus]',
            'label' => 'availabilityStatus',
            'required' => 'false',
            'placeholder' => 'availabilityStatus',
        ],
        [
            'type' => 'text',
            'name' => 'filter[returnPolicy]',
            'label' => 'returnPolicy',
            'required' => 'false',
            'placeholder' => 'returnPolicy',
        ],
        [
            'type' => 'number',
            'name' => 'filter[minimumOrderQuantity]',
            'label' => 'minimumOrderQuantity',
            'required' => 'false',
            'placeholder' => 'minimumOrderQuantity',
        ],
    ],
])
